workflows:
  unity-build:
    name: Unity Build - IceFishing
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      unity: 2022.3.62f1
      vars:
        BUILD_PLATFORM: android
      groups:
        - unity_credentials  # сюда входят UNITY_SERIAL, UNITY_EMAIL, UNITY_PASSWORD, а также CM_KEY_ALIAS, CM_KEYSTORE_PASSWORD, CM_KEY_PASSWORD
    scripts:
      - name: Activate Unity license
        script: |
          echo "Activating Unity license..."
          "$UNITY_HOME/Contents/MacOS/Unity" -batchmode \
            -quit \
            -logFile unity_license.log \
            -serial $UNITY_SERIAL \
            -username $UNITY_EMAIL \
            -password $UNITY_PASSWORD

  unity-return-license:
    name: Unity Return License
    max_build_duration: 10
    scripts:
      - name: Return Unity license
        ignore_failure: true
        script: |
          echo "Returning Unity license..."
          "$UNITY_HOME/Contents/MacOS/Unity" \
            -batchmode -quit -returnLicense || true
