workflows:
  unity-build:
    name: Unity Build - IceFishing
    instance_type: mac_mini_m2
    max_build_duration: 180
    caching:
      enabled: true
      paths:
        - Library
        - obj
        - Logs
        - UserSettings
    environment:
      unity: 2022.3.62f1
      vars:
        BUILD_PLATFORM: android
      groups:
        - unity_credentials
    scripts:
      - name: Activate Unity license
        script: |
          "$UNITY_HOME/Contents/MacOS/Unity" -batchmode \
            -quit \
            -logFile unity_license.log \
            -serial $UNITY_SERIAL \
            -username $UNITY_EMAIL \
            -password $UNITY_PASSWORD
      - name: Build the project
        script: |
          echo "Building Unity project..."
          "$UNITY_HOME/Contents/MacOS/Unity" -batchmode \
            -quit \
            -logFile unity_build.log \
            -projectPath . \
            -executeMethod BuildScript.PerformBuild \
            -nographics
    artifacts:
      - IceFishing.aab
      - IceFishing.apk
      - unity_build.log
      - unity_license.log
